sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t8oYQRTn4X2Ejr5bX7x
    access-key-secret: 8xAQ4JnlLQ1wHgVA8yAczcr9IrxL2D
    bucket-name: sky-take-out-kzmqvq
